// Build-time: scan app/dist and emit src/embedded-manifest.ts with one
// `import … with { type: "file" }` per asset (so `bun build --compile` embeds
// them) plus an ASSETS map from url path -> embedded file path. Generated
// content is NOT committed; a `{}` stub lives in git for dev/test.
import { readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

export function listFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((n) => {
    const abs = join(dir, n);
    return statSync(abs).isDirectory() ? listFiles(abs) : [abs];
  });
}

export function renderManifest(distDir: string, fromDir: string): string {
  const files = listFiles(distDir);
  let out = "// AUTO-GENERATED by scripts/gen-embedded.ts — do not edit, do not commit real content.\n";
  const entries: string[] = [];
  files.forEach((abs, i) => {
    const urlPath = "/" + relative(distDir, abs).split("\\").join("/");
    const imp = "./" + relative(fromDir, abs).split("\\").join("/");
    out += `import a${i} from ${JSON.stringify(imp)} with { type: "file" };\n`;
    entries.push(`  [${JSON.stringify(urlPath)}, a${i}]`);
  });
  out += `\nexport const ASSETS: Record<string, string> = Object.fromEntries([\n${entries.join(",\n")}\n]);\n`;
  return out;
}

if (import.meta.main) {
  const distDir = join(import.meta.dir, "../../app/dist");
  const fromDir = join(import.meta.dir, "../src"); // manifest lives in src/
  const target = join(fromDir, "embedded-manifest.ts");
  await Bun.write(target, renderManifest(distDir, fromDir));
  console.log("[gen-embedded] wrote", target, `(${listFiles(distDir).length} files)`);
}
