import "./app.css";
import "./fonts.css";
import "./theme-tokens.css"; // generated by `bun run gen:themes`; after app.css so theme values win
import "@xterm/xterm/css/xterm.css";
import App from "./App.svelte";
import { mount } from "svelte";
import { initThemeAsync } from "./lib/theme";
import { initFont } from "./lib/font";
import { setupI18n } from "./lib/i18n";

// Apply <html data-font> before first render (index.html has the same guard
// inline). Synchronous — no network round trip needed for a font choice, so
// it does not need to join the theme promise chain below.
initFont();

// Apply <html data-theme> before first render (index.html has the same guard
// inline).
//
// This is a promise chain rather than a top-level `await` because the build
// targets safari14, which has neither. It is asynchronous at all because a user
// on a *custom* theme needs one more request first: the <link> in the HTML has
// no `?t=`, so it brings back the manifest but not that theme's tokens (the
// agent only expands the selected one — design §4.5), and mounting before it
// lands would paint the whole app in the default palette for the length of that
// round trip. On a built-in theme it resolves in the same microtask without
// touching the network, so the common path is unchanged.
void initThemeAsync().then(() => {
  setupI18n(); // init svelte-i18n before mount so no raw keys flash
  mount(App, { target: document.getElementById("app")! });
});

// PWA: register the versioned service worker (public/sw.js) in production
// builds only — dev uses vite HMR and must not be intercepted.
//
// The ?v= query is load-bearing: the browser treats a changed registration URL
// as a new worker and runs install/activate, which is how a release swaps cache
// buckets. Same version => identical URL => no-op, which is exactly the
// "no version change, just serve from cache" case.
// 演示站不注册 SW：① 访客把「演示沙盘」装到桌面会认错产品；② 版本桶缓存会
// 让改完的演示推上去、访客仍看旧的。
if (import.meta.env.PROD && import.meta.env.VITE_POCKETSHELL_DEMO !== "1" && "serviceWorker" in navigator) {
  window.addEventListener("load", () =>
    void navigator.serviceWorker.register(`/sw.js?v=${__APP_VERSION__}`),
  );
}
