// Built-in frequently-used commands for the smart hint bar. Pure static data.
// A trailing space (e.g. "cd ") means "prefix that expects an argument"; a single
// tap still inserts it and leaves the cursor ready for the argument.
export const CATALOG: string[] = [
  "git status",
  "git add ",
  "git add .",
  "git commit",
  'git commit -m ""',
  "git push",
  "git pull",
  "git log --oneline",
  "git diff",
  "git checkout ",
  "git branch",
  "npm install",
  "npm run ",
  "npm test",
  "npm run build",
  "bun install",
  "bun run ",
  "bun test",
  "bun run build",
  "docker ps",
  "docker logs ",
  "docker compose up",
  "docker exec -it ",
  "claude",
  "cd ",
  "ls",
  "ls -la",
  "cat ",
  "grep -r ",
  "tail -f ",
  "chmod +x ",
  "kill ",
  "pwd",
  "clear",
];
