// Idempotent auto-wiring of each tool's hook config. Only ever adds/removes our
// own marked entry (command === "<agentBin> notify"); never touches the user's
// other hooks. Every failure returns a structured {ok:false, reason, detail}
// the UI surfaces — no silent failure.
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join as joinPath } from "node:path";

export interface WireResult { ok: boolean; reason?: string; detail?: string; }
const notifyCmd = (agentBin: string) => `${agentBin} notify`;

export function wireClaude(settingsPath: string, agentBin: string): WireResult {
  let root: any = {};
  if (existsSync(settingsPath)) {
    try { root = JSON.parse(readFileSync(settingsPath, "utf8")); }
    catch (e) { return { ok: false, reason: "parse_error", detail: String(e) }; }
  }
  const cmd = notifyCmd(agentBin);
  root.hooks ??= {};
  const list: any[] = Array.isArray(root.hooks.Notification) ? root.hooks.Notification : (root.hooks.Notification = []);
  const already = list.some((e) => Array.isArray(e.hooks) && e.hooks.some((h: any) => h.command === cmd));
  if (!already) list.push({ matcher: "", hooks: [{ type: "command", command: cmd }] });
  try {
    mkdirSync(dirname(settingsPath), { recursive: true });
    writeFileSync(settingsPath, JSON.stringify(root, null, 2));
  } catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireClaude(settingsPath: string): WireResult {
  if (!existsSync(settingsPath)) return { ok: true };
  let root: any;
  try { root = JSON.parse(readFileSync(settingsPath, "utf8")); }
  catch (e) { return { ok: false, reason: "parse_error", detail: String(e) }; }
  const list: any[] = root?.hooks?.Notification;
  if (Array.isArray(list)) {
    root.hooks.Notification = list
      .map((e) => (Array.isArray(e.hooks) ? { ...e, hooks: e.hooks.filter((h: any) => !String(h.command ?? "").endsWith(" notify")) } : e))
      .filter((e) => !Array.isArray(e.hooks) || e.hooks.length > 0);
  }
  try { writeFileSync(settingsPath, JSON.stringify(root, null, 2)); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

const codexLine = (agentBin: string) => `notify = ["${agentBin}", "notify"]`;
const isOurCodexNotify = (line: string, agentBin: string) => line.trim() === codexLine(agentBin);

export function wireCodex(configPath: string, agentBin: string): WireResult {
  let text = "";
  if (existsSync(configPath)) {
    try { text = readFileSync(configPath, "utf8"); }
    catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  }
  const lines = text.split("\n");
  const notifyLines = lines.filter((l) => l.trimStart().startsWith("notify ="));
  if (notifyLines.some((l) => isOurCodexNotify(l, agentBin))) return { ok: true }; // idempotent
  if (notifyLines.length > 0) return { ok: false, reason: "conflict", detail: "existing notify key" };
  const next = `${codexLine(agentBin)}\n${text}`; // prepend before any [table]
  try { mkdirSync(dirname(configPath), { recursive: true }); writeFileSync(configPath, next); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireCodex(configPath: string): WireResult {
  if (!existsSync(configPath)) return { ok: true };
  let text: string;
  try { text = readFileSync(configPath, "utf8"); }
  catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  const kept = text.split("\n").filter((l) => !(l.trimStart().startsWith("notify =") && l.includes('"notify"')));
  try { writeFileSync(configPath, kept.join("\n")); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

const OPENCODE_PLUGIN = "pocketshell-notify.js";
const OPENCODE_PLUGIN_SRC = `// Auto-generated by PocketShell. Removed when you disable opencode notifications.
export const PocketShellNotify = async () => ({
  event: async ({ event }) => {
    if (event.type !== "session.idle") return;
    const url = process.env.POCKETSHELL_NOTIFY_URL, token = process.env.POCKETSHELL_NOTIFY_TOKEN, session = process.env.POCKETSHELL_NOTIFY_SESSION;
    if (!url || !token || !session) return;
    await fetch(url, { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer " + token }, body: JSON.stringify({ sessionId: session, title: session, body: "" }) }).catch(() => {});
  },
});
`;

export function wireOpencode(pluginDir: string): WireResult {
  // pluginDir is <opencodeConfig>/plugin. If the opencode config base doesn't
  // exist at all, treat it as "opencode not installed" rather than creating a
  // stray ~/.config/opencode tree.
  if (!existsSync(dirname(pluginDir))) return { ok: false, reason: "opencode_not_found", detail: dirname(pluginDir) };
  try {
    mkdirSync(pluginDir, { recursive: true });
    writeFileSync(joinPath(pluginDir, OPENCODE_PLUGIN), OPENCODE_PLUGIN_SRC);
  } catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireOpencode(pluginDir: string): WireResult {
  try { rmSync(joinPath(pluginDir, OPENCODE_PLUGIN), { force: true }); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}
