// Idempotent auto-wiring of each tool's hook config. Only ever adds/removes our
// own marked entry; never touches the user's other hooks. Every failure returns
// a structured {ok:false, reason, detail} the UI surfaces — no silent failure.
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join as joinPath } from "node:path";

export interface WireResult { ok: boolean; reason?: string; detail?: string; }

// ---- claude code ----
// 新版命令把工具名作为参数带进去，这样 notify 子命令才知道该读哪个落盘文件。
// 同时兼容旧版 `pocketshell-agent notify`：wire/unwire 都会把旧命令清理掉。
const notifyCmd = (agentBin: string) => `${agentBin} notify claude`;
const oldNotifyCmd = (agentBin: string) => `${agentBin} notify`;
const isOurNotifyCmd = (agentBin: string, command: string) =>
  command === notifyCmd(agentBin) || command === oldNotifyCmd(agentBin);

export function wireClaude(settingsPath: string, agentBin: string): WireResult {
  let root: any = {};
  if (existsSync(settingsPath)) {
    try { root = JSON.parse(readFileSync(settingsPath, "utf8")); }
    catch (e) { return { ok: false, reason: "parse_error", detail: String(e) }; }
  }
  const cmd = notifyCmd(agentBin);
  root.hooks ??= {};
  const list: any[] = Array.isArray(root.hooks.Notification) ? root.hooks.Notification : (root.hooks.Notification = []);

  // 幂等：移除我们已有的旧/新命令（包括迁移旧版接线）。
  for (const e of list) {
    if (Array.isArray(e.hooks)) e.hooks = e.hooks.filter((h: any) => !isOurNotifyCmd(agentBin, h.command));
  }
  const cleaned = list.filter((e) => !Array.isArray(e.hooks) || e.hooks.length > 0);
  root.hooks.Notification = cleaned;

  cleaned.push({ matcher: "", hooks: [{ type: "command", command: cmd }] });
  try {
    mkdirSync(dirname(settingsPath), { recursive: true });
    writeFileSync(settingsPath, JSON.stringify(root, null, 2));
  } catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireClaude(settingsPath: string, agentBin: string): WireResult {
  if (!existsSync(settingsPath)) return { ok: true };
  let root: any;
  try { root = JSON.parse(readFileSync(settingsPath, "utf8")); }
  catch (e) { return { ok: false, reason: "parse_error", detail: String(e) }; }
  const list: any[] = root?.hooks?.Notification;
  if (Array.isArray(list)) {
    root.hooks.Notification = list
      .map((e) => (Array.isArray(e.hooks) ? { ...e, hooks: e.hooks.filter((h: any) => !isOurNotifyCmd(agentBin, h.command)) } : e))
      .filter((e) => !Array.isArray(e.hooks) || e.hooks.length > 0);
  }
  try { writeFileSync(settingsPath, JSON.stringify(root, null, 2)); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

// ---- codex ----
const codexLine = (agentBin: string) => `notify = ["${agentBin}", "notify", "codex"]`;
const isOurCodexNotify = (line: string, agentBin: string) => line.trimStart().startsWith(`notify = ["${agentBin}", "notify"`);

export function wireCodex(configPath: string, agentBin: string): WireResult {
  let text = "";
  if (existsSync(configPath)) {
    try { text = readFileSync(configPath, "utf8"); }
    catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  }
  const lines = text.split("\n");
  const notifyLines = lines.filter((l) => l.trimStart().startsWith("notify ="));
  if (notifyLines.some((l) => isOurCodexNotify(l, agentBin))) return { ok: true }; // idempotent
  if (notifyLines.length > 0) return { ok: false, reason: "conflict", detail: "existing notify key" };
  const next = `${codexLine(agentBin)}\n${text}`; // prepend before any [table]
  try { mkdirSync(dirname(configPath), { recursive: true }); writeFileSync(configPath, next); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireCodex(configPath: string): WireResult {
  if (!existsSync(configPath)) return { ok: true };
  let text: string;
  try { text = readFileSync(configPath, "utf8"); }
  catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  const kept = text.split("\n").filter((l) => !(l.trimStart().startsWith("notify =") && l.includes('"notify"')));
  try { writeFileSync(configPath, kept.join("\n")); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

// ---- opencode ----
const OPENCODE_PLUGIN = "pocketshell-notify.js";
const OPENCODE_PLUGIN_SRC = `// Auto-generated by PocketShell. Removed when you disable opencode notifications.
//
// token 用量走 SDK 而不是读 opencode 的落盘文件：它的存储格式版本不稳定
// （旧版 JSON、新版 SQLite），官方工具明确警告不要解析。
// 取不到 token 时照常发通知 —— token 是搭车的，不能反过来卡住通知主线。
export const PocketShellNotify = async ({ client }) => ({
  event: async ({ event }) => {
    if (event.type !== "session.idle") return;
    const url = process.env.POCKETSHELL_NOTIFY_URL, token = process.env.POCKETSHELL_NOTIFY_TOKEN, session = process.env.POCKETSHELL_NOTIFY_SESSION;
    if (!url || !token || !session) return;

    let ctx = {};
    try {
      const sid = event.properties?.sessionID;
      if (sid && client) {
        const msgs = await client.session.messages({ path: { id: sid } });
        const list = Array.isArray(msgs?.data) ? msgs.data : [];
        for (let i = list.length - 1; i >= 0; i--) {
          const t = list[i]?.info?.tokens;
          if (!t) continue;
          const used = (t.input || 0) + (t.output || 0) + (t.cache?.read || 0) + (t.cache?.write || 0);
          if (used > 0) { ctx = { tool: "opencode", ctxUsed: used }; break; }
        }
      }
    } catch {}

    await fetch(url, { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer " + token }, body: JSON.stringify({ sessionId: session, title: session, body: "", ...ctx }) }).catch(() => {});
  },
});
`;

export function wireOpencode(pluginDir: string): WireResult {
  if (!existsSync(dirname(pluginDir))) return { ok: false, reason: "opencode_not_found", detail: dirname(pluginDir) };
  try {
    mkdirSync(pluginDir, { recursive: true });
    writeFileSync(joinPath(pluginDir, OPENCODE_PLUGIN), OPENCODE_PLUGIN_SRC);
  } catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireOpencode(pluginDir: string): WireResult {
  try { rmSync(joinPath(pluginDir, OPENCODE_PLUGIN), { force: true }); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

// ---- kimi-cli ----
// 配置在 ~/.kimi/config.toml 的 [[hooks]] 数组表。
//
// 三处与直觉不符、来自本机 1.49.0 源码实证的事实：
//   1) 路径是 ~/.kimi 而非官方文档写的 ~/.kimi-code —— 见 share.py 的
//      get_share_dir() = Path.home()/".kimi"（KIMI_SHARE_DIR 可覆盖）。
//      文档与实现不一致，以实现为准；kimi 若改了这里需要跟进。
//   2) 用 Stop 事件而不是 Notification —— kimi 的 Notification 只在后台任务
//      状态变化时触发，日常回合结束不触发；Stop 才对应「一轮跑完」，语义上
//      等同 claude 的 Notification。
//   3) 只写 event 和 command 两个字段 —— hooks/config.py 的 HookDef 是
//      pydantic 模型，多写任何字段会让整个 config.toml 加载失败（kimi 起不来）。
//      matcher/timeout 一律不写，用默认值。
//
// [[hooks]] 是数组表，追加不与用户已有条目冲突（与 codex 的单键 notify=
// 不同），所以没有 conflict 分支。用标记注释锚定我们这块以便精确移除。
const KIMI_MARK = "# pocketshell-notify";
const kimiBlock = (agentBin: string) =>
  `${KIMI_MARK}\n[[hooks]]\nevent = "Stop"\ncommand = "${agentBin} notify kimi"\n`;

export function wireKimi(configPath: string, agentBin: string): WireResult {
  // 判定 kimi 是否安装：配置目录存在即可。不存在就不建 —— 与 opencode 的
  // opencode_not_found 同款保守策略，别给没装的工具留下一棵孤儿目录树。
  if (!existsSync(dirname(configPath))) {
    return { ok: false, reason: "kimi_not_found", detail: dirname(configPath) };
  }
  let text = "";
  if (existsSync(configPath)) {
    try { text = readFileSync(configPath, "utf8"); }
    catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  }
  if (text.includes(KIMI_MARK)) return { ok: true }; // 幂等
  const next = text.endsWith("\n") || text === "" ? text + kimiBlock(agentBin)
                                                  : text + "\n" + kimiBlock(agentBin);
  try { writeFileSync(configPath, next); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireKimi(configPath: string): WireResult {
  if (!existsSync(configPath)) return { ok: true };
  let text: string;
  try { text = readFileSync(configPath, "utf8"); }
  catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  try { writeFileSync(configPath, stripKimiBlock(text)); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function stripKimiBlock(text: string): string {
  const lines = text.split("\n");
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    if (lines[i].trim() !== KIMI_MARK) { out.push(lines[i]); i++; continue; }
    i++;                                             // 跳过标记行
    if (i < lines.length && lines[i].trim() === "[[hooks]]") i++;  // 跳过表头
    while (i < lines.length && !lines[i].trimStart().startsWith("[") && lines[i].trim() !== "") i++;
    while (i < lines.length && lines[i].trim() === "") i++;        // 吞掉块后空行
  }
  return out.join("\n");
}
