// Idempotent auto-wiring of each tool's hook config. Only ever adds/removes our
// own marked entry; never touches the user's other hooks. Every failure returns
// a structured {ok:false, reason, detail} the UI surfaces — no silent failure.
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join as joinPath } from "node:path";

export interface WireResult { ok: boolean; reason?: string; detail?: string; }

// ---- claude code ----
// 新版命令把工具名作为参数带进去，这样 notify 子命令才知道该读哪个落盘文件。
// 同时兼容旧版 `pocketshell-agent notify`：wire/unwire 都会把旧命令清理掉。
const notifyCmd = (agentBin: string) => `${agentBin} notify claude`;
const oldNotifyCmd = (agentBin: string) => `${agentBin} notify`;
const isOurNotifyCmd = (agentBin: string, command: string) =>
  command === notifyCmd(agentBin) || command === oldNotifyCmd(agentBin);

export function wireClaude(settingsPath: string, agentBin: string): WireResult {
  let root: any = {};
  if (existsSync(settingsPath)) {
    try { root = JSON.parse(readFileSync(settingsPath, "utf8")); }
    catch (e) { return { ok: false, reason: "parse_error", detail: String(e) }; }
  }
  const cmd = notifyCmd(agentBin);
  root.hooks ??= {};
  const list: any[] = Array.isArray(root.hooks.Notification) ? root.hooks.Notification : (root.hooks.Notification = []);

  // 幂等：移除我们已有的旧/新命令（包括迁移旧版接线）。
  for (const e of list) {
    if (Array.isArray(e.hooks)) e.hooks = e.hooks.filter((h: any) => !isOurNotifyCmd(agentBin, h.command));
  }
  const cleaned = list.filter((e) => !Array.isArray(e.hooks) || e.hooks.length > 0);
  root.hooks.Notification = cleaned;

  cleaned.push({ matcher: "", hooks: [{ type: "command", command: cmd }] });
  try {
    mkdirSync(dirname(settingsPath), { recursive: true });
    writeFileSync(settingsPath, JSON.stringify(root, null, 2));
  } catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireClaude(settingsPath: string, agentBin: string): WireResult {
  if (!existsSync(settingsPath)) return { ok: true };
  let root: any;
  try { root = JSON.parse(readFileSync(settingsPath, "utf8")); }
  catch (e) { return { ok: false, reason: "parse_error", detail: String(e) }; }
  const list: any[] = root?.hooks?.Notification;
  if (Array.isArray(list)) {
    root.hooks.Notification = list
      .map((e) => (Array.isArray(e.hooks) ? { ...e, hooks: e.hooks.filter((h: any) => !isOurNotifyCmd(agentBin, h.command)) } : e))
      .filter((e) => !Array.isArray(e.hooks) || e.hooks.length > 0);
  }
  try { writeFileSync(settingsPath, JSON.stringify(root, null, 2)); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

// ---- codex ----
const codexLine = (agentBin: string) => `notify = ["${agentBin}", "notify", "codex"]`;
const isOurCodexNotify = (line: string, agentBin: string) => line.trimStart().startsWith(`notify = ["${agentBin}", "notify"`);

export function wireCodex(configPath: string, agentBin: string): WireResult {
  let text = "";
  if (existsSync(configPath)) {
    try { text = readFileSync(configPath, "utf8"); }
    catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  }
  const lines = text.split("\n");
  const notifyLines = lines.filter((l) => l.trimStart().startsWith("notify ="));
  if (notifyLines.some((l) => isOurCodexNotify(l, agentBin))) return { ok: true }; // idempotent
  if (notifyLines.length > 0) return { ok: false, reason: "conflict", detail: "existing notify key" };
  const next = `${codexLine(agentBin)}\n${text}`; // prepend before any [table]
  try { mkdirSync(dirname(configPath), { recursive: true }); writeFileSync(configPath, next); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireCodex(configPath: string): WireResult {
  if (!existsSync(configPath)) return { ok: true };
  let text: string;
  try { text = readFileSync(configPath, "utf8"); }
  catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  const kept = text.split("\n").filter((l) => !(l.trimStart().startsWith("notify =") && l.includes('"notify"')));
  try { writeFileSync(configPath, kept.join("\n")); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

// ---- opencode ----
const OPENCODE_PLUGIN = "pocketshell-notify.js";
const OPENCODE_PLUGIN_SRC = `// Auto-generated by PocketShell. Removed when you disable opencode notifications.
//
// token 用量走 SDK 而不是读 opencode 的落盘文件：它的存储格式版本不稳定
// （旧版 JSON、新版 SQLite），官方工具明确警告不要解析。
// 取不到 token 时照常发通知 —— token 是搭车的，不能反过来卡住通知主线。
export const PocketShellNotify = async ({ client }) => ({
  event: async ({ event }) => {
    if (event.type !== "session.idle") return;
    const url = process.env.POCKETSHELL_NOTIFY_URL, token = process.env.POCKETSHELL_NOTIFY_TOKEN, session = process.env.POCKETSHELL_NOTIFY_SESSION;
    if (!url || !token || !session) return;

    let ctx = {};
    try {
      const sid = event.properties?.sessionID;
      if (sid && client) {
        const msgs = await client.session.messages({ path: { id: sid } });
        const list = Array.isArray(msgs?.data) ? msgs.data : [];
        for (let i = list.length - 1; i >= 0; i--) {
          const t = list[i]?.info?.tokens;
          if (!t) continue;
          const used = (t.input || 0) + (t.output || 0) + (t.cache?.read || 0) + (t.cache?.write || 0);
          if (used > 0) { ctx = { tool: "opencode", ctxUsed: used }; break; }
        }
      }
    } catch {}

    await fetch(url, { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer " + token }, body: JSON.stringify({ sessionId: session, title: session, body: "", ...ctx }) }).catch(() => {});
  },
});
`;

export function wireOpencode(pluginDir: string): WireResult {
  if (!existsSync(dirname(pluginDir))) return { ok: false, reason: "opencode_not_found", detail: dirname(pluginDir) };
  try {
    mkdirSync(pluginDir, { recursive: true });
    writeFileSync(joinPath(pluginDir, OPENCODE_PLUGIN), OPENCODE_PLUGIN_SRC);
  } catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireOpencode(pluginDir: string): WireResult {
  try { rmSync(joinPath(pluginDir, OPENCODE_PLUGIN), { force: true }); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

// ---- kimi-cli ----
// 配置在 ~/.kimi/config.toml 的 [[hooks]] 数组表。
//
// 三处与直觉不符、来自本机 1.49.0 源码实证的事实：
//   1) 路径是 ~/.kimi 而非官方文档写的 ~/.kimi-code —— 见 share.py 的
//      get_share_dir() = Path.home()/".kimi"（KIMI_SHARE_DIR 可覆盖）。
//      文档与实现不一致，以实现为准；kimi 若改了这里需要跟进。
//   2) 用 Stop 事件而不是 Notification —— kimi 的 Notification 只在后台任务
//      状态变化时触发，日常回合结束不触发；Stop 才对应「一轮跑完」，语义上
//      等同 claude 的 Notification。
//   3) 只写 event 和 command 两个字段 —— hooks/config.py 的 HookDef 是
//      pydantic 模型，多写任何字段会让整个 config.toml 加载失败（kimi 起不来）。
//      matcher/timeout 一律不写，用默认值。
//
// ⚠️ 真机踩坑（2026-07-31，写坏过用户的 kimi）：**不能无脑追加 [[hooks]]**。
// kimi 生成的默认 config.toml 里带一行 `hooks = []`，此时再追加一个
// `[[hooks]]` 数组表，TOML 规范判定同一个键被定义两次，kimi 直接拒绝加载：
//   Invalid TOML: Key "hooks" already exists. at line 95 col 0
// 于是 kimi 完全起不来——这正是第 3 条注释警告的那类后果，只是触发点在
// 键的形态而不是字段数量。
//
// 因此按现场形态分派（四种都实测过 kimi 能正常加载）：
//   A. 有 `hooks = [...]`（含空数组）→ 往该数组里插一个**行内表**，不新增表头
//   B. 没有 hooks 键，但有 `[[hooks]]` 数组表 → 追加一个 [[hooks]] 块
//   C. 两者都没有 → 追加一个 [[hooks]] 块
// 标记注释都放在同一行/紧邻行，以便 unwire 精确定位。
const KIMI_MARK = "# pocketshell-notify";
const kimiInline = (agentBin: string) =>
  `{ event = "Stop", command = "${agentBin} notify kimi" }`;
const kimiBlock = (agentBin: string) =>
  `${KIMI_MARK}\n[[hooks]]\nevent = "Stop"\ncommand = "${agentBin} notify kimi"\n`;

// 找到顶层的 `hooks = [` 那一行（不能匹配 `[mcp]` 段里的同名键，故要求
// 行首无缩进；kimi 的默认配置就是顶层裸键）。返回行号，找不到返回 -1。
function findHooksArrayLine(lines: string[]): number {
  return lines.findIndex((l) => /^hooks\s*=\s*\[/.test(l));
}

export function wireKimi(configPath: string, agentBin: string): WireResult {
  // 判定 kimi 是否安装：配置目录存在即可。不存在就不建 —— 与 opencode 的
  // opencode_not_found 同款保守策略，别给没装的工具留下一棵孤儿目录树。
  if (!existsSync(dirname(configPath))) {
    return { ok: false, reason: "kimi_not_found", detail: dirname(configPath) };
  }
  let text = "";
  if (existsSync(configPath)) {
    try { text = readFileSync(configPath, "utf8"); }
    catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  }
  if (text.includes(KIMI_MARK)) return { ok: true }; // 幂等

  const lines = text.split("\n");
  const hooksLine = findHooksArrayLine(lines);
  let next: string;

  if (hooksLine >= 0) {
    // 形态 A：已有 hooks 数组。必须往数组里塞行内表——另起 [[hooks]] 会
    // 撞成 "Key hooks already exists" 让 kimi 整个起不来。
    const l = lines[hooksLine];
    const open = l.indexOf("[");
    const close = l.lastIndexOf("]");
    // 只处理单行数组（kimi 自己生成的就是单行）。多行数组形态不认识时
    // 宁可报错也不要瞎改——写坏 config.toml 的代价是 kimi 完全打不开。
    if (close <= open) {
      return { ok: false, reason: "conflict", detail: "multi-line hooks array; edit ~/.kimi/config.toml manually" };
    }
    const inner = l.slice(open + 1, close).trim();
    const merged = inner === "" ? kimiInline(agentBin) : `${inner}, ${kimiInline(agentBin)}`;
    lines[hooksLine] = `hooks = [${merged}]  ${KIMI_MARK}`;
    next = lines.join("\n");
  } else {
    // 形态 B/C：没有 hooks 裸键。追加数组表是安全的——TOML 允许同名
    // [[hooks]] 多次出现（那正是数组表的语义）。
    next = text.endsWith("\n") || text === "" ? text + kimiBlock(agentBin)
                                              : text + "\n" + kimiBlock(agentBin);
  }

  try { writeFileSync(configPath, next); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function unwireKimi(configPath: string): WireResult {
  if (!existsSync(configPath)) return { ok: true };
  let text: string;
  try { text = readFileSync(configPath, "utf8"); }
  catch (e) { return { ok: false, reason: "read_error", detail: String(e) }; }
  try { writeFileSync(configPath, stripKimiBlock(text)); }
  catch (e) { return { ok: false, reason: "write_error", detail: String(e) }; }
  return { ok: true };
}

export function stripKimiBlock(text: string): string {
  const lines = text.split("\n");
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    // 形态 A 的还原：带标记的 hooks 行内数组，摘掉我们那一项，
    // 保留用户的其余项；只剩空数组就还原成 `hooks = []`。
    if (lines[i].includes(KIMI_MARK) && /^hooks\s*=\s*\[/.test(lines[i])) {
      const l = lines[i];
      const open = l.indexOf("[");
      const close = l.lastIndexOf("]");
      const inner = close > open ? l.slice(open + 1, close) : "";
      const kept = splitInlineTables(inner).filter((t) => !/pocketshell-agent["']?\s+notify/.test(t) && !t.includes("notify kimi"));
      out.push(`hooks = [${kept.join(", ")}]`);
      i++;
      continue;
    }
    if (lines[i].trim() !== KIMI_MARK) { out.push(lines[i]); i++; continue; }
    i++;                                             // 跳过标记行
    if (i < lines.length && lines[i].trim() === "[[hooks]]") i++;  // 跳过表头
    while (i < lines.length && !lines[i].trimStart().startsWith("[") && lines[i].trim() !== "") i++;
    while (i < lines.length && lines[i].trim() === "") i++;        // 吞掉块后空行
  }
  return out.join("\n");
}

// 把 `{a=1}, {b=2}` 这样的行内表列表按顶层逗号切开（不能直接 split(",")：
// 表内部也有逗号）。只需处理 `{}` 一层嵌套与引号，kimi 的 hooks 项就这形态。
function splitInlineTables(inner: string): string[] {
  const out: string[] = [];
  let depth = 0, quote = "", cur = "";
  for (const ch of inner) {
    if (quote) { cur += ch; if (ch === quote) quote = ""; continue; }
    if (ch === '"' || ch === "'") { quote = ch; cur += ch; continue; }
    if (ch === "{") depth++;
    if (ch === "}") depth--;
    if (ch === "," && depth === 0) { const t = cur.trim(); if (t) out.push(t); cur = ""; continue; }
    cur += ch;
  }
  const t = cur.trim();
  if (t) out.push(t);
  return out;
}
