// Pure routing for same-port frontend serving. server.ts turns a StaticResult
// into a Response via Bun.file(ASSETS[assetKey]). Keys are url paths, e.g.
// "/assets/x.js"; precompressed variants live at "<key>.br" / "<key>.gz".
// ETag / 304 helpers are pure functions so they stay unit-testable here.
import { createHash } from "node:crypto";

export interface StaticResult {
  status: 200 | 404;
  assetKey?: string;
  headers: Record<string, string>;
  /** Explicit Content-Type — required for .br/.gz variants (Bun.file infers the wrong type from those extensions). */
  contentType?: string;
}

const IMMUTABLE = "public, max-age=31536000, immutable";
const NO_CACHE = "no-cache";

// MIME map used only for compressed variants; uncompressed files keep relying
// on Bun.file's extension inference.
const MIME: Record<string, string> = {
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".svg": "image/svg+xml",
  ".json": "application/json",
  ".webmanifest": "application/manifest+json",
};

function extOf(path: string): string {
  const i = path.lastIndexOf(".");
  return i === -1 ? "" : path.slice(i).toLowerCase();
}

function acceptedEncodings(acceptEncoding: string): Set<string> {
  return new Set(
    acceptEncoding
      .toLowerCase()
      .split(",")
      .map((s) => s.trim().split(";")[0].trim())
      .filter(Boolean),
  );
}

export function resolveStatic(
  pathname: string,
  accept: string,
  assetKeys: Set<string>,
  acceptEncoding = "",
): StaticResult {
  const key = pathname === "/" ? "/index.html" : pathname;
  const immutable = key.startsWith("/assets/"); // vite emits content-hashed names here
  const cacheControl = immutable ? IMMUTABLE : NO_CACHE;

  if (assetKeys.has(key)) {
    // Precompressed siblings generated by app/scripts/compress-dist.ts. When
    // they exist the response varies on Accept-Encoding even if we end up
    // serving the identity variant.
    const hasBr = assetKeys.has(`${key}.br`);
    const hasGz = assetKeys.has(`${key}.gz`);
    if (hasBr || hasGz) {
      const encodings = acceptedEncodings(acceptEncoding);
      const headers: Record<string, string> = {
        "Cache-Control": cacheControl,
        Vary: "Accept-Encoding",
      };
      const contentType = MIME[extOf(key)] ?? "application/octet-stream";
      if (hasBr && encodings.has("br")) {
        headers["Content-Encoding"] = "br";
        return { status: 200, assetKey: `${key}.br`, headers, contentType };
      }
      if (hasGz && encodings.has("gzip")) {
        headers["Content-Encoding"] = "gzip";
        return { status: 200, assetKey: `${key}.gz`, headers, contentType };
      }
      return { status: 200, assetKey: key, headers };
    }
    return { status: 200, assetKey: key, headers: { "Cache-Control": cacheControl } };
  }
  // SPA fallback: navigation requests (Accept: text/html) get the shell so
  // client-side routing works; asset misses stay 404.
  if (accept.includes("text/html") && assetKeys.has("/index.html")) {
    return resolveStatic("/", accept, assetKeys, acceptEncoding);
  }
  return { status: 404, headers: {} };
}

/** Strong ETag for a body: truncated sha256, quoted per RFC 7232. */
export function contentEtag(body: Uint8Array | ArrayBuffer): string {
  const data = body instanceof Uint8Array ? body : new Uint8Array(body);
  return `"${createHash("sha256").update(data).digest("hex").slice(0, 16)}"`;
}

/** RFC 7232 If-None-Match check for strong comparison (exact match or "*"). */
export function isNotModified(ifNoneMatch: string | null, etag: string): boolean {
  if (!ifNoneMatch) return false;
  for (const candidate of ifNoneMatch.split(",")) {
    const c = candidate.trim();
    if (c === "*") return true;
    // Tolerate weak validators on identical representations (W/"…").
    if (c === etag || (c.startsWith("W/") && c.slice(2) === etag)) return true;
  }
  return false;
}
